remote_theme: mmistakes/minimal-mistakes@4.24.0
plugins:
  - jekyll-include-cache
  
title: "Ritah Nabunje"
description: "Research, blogs, and science policy reflections"
email: "rn180@leicester.ac.uk"
url: "https://ritah-nabunje.github.io"
baseurl: ""

author:
  name: "Ritah Nabunje"
  avatar: "/assets/images/profile.jpg"
  bio: "PhD researcher in human genomics."

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      author_profile: true

collections:
  posts:
    output: true

# Load nav from _data/navigation.yml
