
title: "Ritah Nabunje"
description: "About me"
url: "https://ritah-nabunje.github.io"
baseurl: ""

theme: jekyll-academic

author:
  name: "Ritah Nabunje"
  email: "rn180@leicester.ac.uk"
  linkedin: "https://www.linkedin.com/in/ritah-nabunje/"

social:
  twitter: ritah_nabunje
  github: ritah-nabunje

plugins:
  - jekyll-feed
  - jekyll-seo-tag

navigation:
  - title: "Home"
    url: "/"
  - title: "Background"
    url: "/background/"
  - title: "Research"
    url: "/research/"
  - title: "Interests"
    url: "/interests/"
  - title: "Contact"
    url: "/contact/"
