remote_theme: mmistakes/minimal-mistakes@4.24.0
plugins:
  - jekyll-include-cache
  - jekyll-paginate-v2

  
title: "Ritah Nabunje"
description: "Research, interests and reflections"
email: "rn180@leicester.ac.uk"
url: "https://ritah-nabunje.github.io"
baseurl: ""

author:
  name: "Ritah Nabunje"
  avatar: "assets/images/profile.jpg"
  bio: "PhD Researcher"
  email: "rn180@leicester.ac.uk"

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      author_profile: true

collections:
  posts:
    output: true
  pages:
    output: true
    permalink: /:path/


# Load nav from _data/navigation.yml
