
remote_theme: mmistakes/minimal-mistakes

title: "Ritah Nabunje"
description: "Genomics | Research | Advocacy"
email: "rn180@leicester.ac.uk"
url: "https://ritah-nabunje.github.io"
baseurl: ""

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

author:
  name: "Ritah Nabunje"
  avatar: "/profile.jpg"
  bio: "PhD student studying genetic risk for pulmonary fibrosis across diverse populations."

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      author_profile: true

collections:
  posts:
    output: true
