# Site settings
title: "Ritah Nabunje"  
description: "About me"
baseurl: "" 
url: "https://ritah-nabunje.github.io"  

# Theme 
theme: jekyll-theme-slate  

author:
  name: "Ritah Nabunje"
  email: "rn180@leicester.ac.uk"
  linkedin: "https://www.linkedin.com/in/ritah-nabunje/"  

# Social media
social:
  twitter_username: ritah_nabunje
  github_username: ritah-nabunje

# Build settings
markdown: kramdown  # Markdown engine 
highlighter: rouge  # Syntax highlighter for code snippets

# Navigation
navigation:
  - title: "Home"
    url: "/"
  - title: "About Me"
    url: "/index.md/"
  - title: "Research"
    url: "/research/"
  - title: "Interests"
    url: "/interests.md/"
  - title: "Contact"
    url: "/contact.md/"

# Plugins
plugins:
  - jekyll-feed   # RSS feed 
  - jekyll-seo-tag  # SEO-friendly tags

# Pagination 
paginate: 5
paginate_path: "/page:num/"
